#!/bin/sh
echo "Content-type: text/html"
echo

#echo argc is $#. argv is "$*".

rootdir="/var/www/html/jumble"
jumbledir="jumbles"
rawfile=$rootdir/raw2

package=$1

if [ "${package%/}" == "$package" ]; then
    package="$package/"
fi

p1=${package%/}
p2=$(echo ${p1#/} | tr '/' '.')
if [ "$p2" == "" ]; then
    p2="root"
fi

echo "<html>"

echo "<head>"
echo "<title>Jumble results for $p2</title>"
echo "</head>"

echo "<body>"

echo "<h1><a href=\"/jumble/key.html\">Jumble</a> results for $p2</h1>"

# average score for this package
score=$(grep $package $rawfile | gawk '{n++; x+=$1} END {print int(x/n)}')
score2=$[$score/10]

echo "<p>The average jumble score for the <b>$p2</b> package is "
echo "<b>$score%</b> <img src=\"/jumble/$score2.gif\">"

date=$(find /share/reeltwo/html/jumble/raw -printf "%TY-%Tm-%Td %TH:%TM:%TS")
echo "<br>Last updated: $date</p>"

echo "<table><tr valign=top><td>"

# links to parent packages
echo "<table bgcolor=#dddddd><tr><td>"

list=""

p2=${package%/*}

while [ "$p2" != "" ]; do
    list="$p2 $list"
    p2=${p2%/*}
done

prev="/"
echo -n "<a href=\"/cgi-bin/jumble-cgi?/\">/</a>"
for l in $list; do
    l2=${l#$prev}
    echo -n "<a href=\"/cgi-bin/jumble-cgi?$l/\">$l2</a>/"
    prev="$l/"
done
echo ""

echo "</td><td></td></tr>"

# subpackage links/summaries

subpackages=$(grep $package $rawfile | gawk '{print $3}' | sed "s|$jumbledir$package||g" | grep '/' | tr '/' ' ' | gawk '{print $1}' | sort | uniq)

for s in $subpackages
do
    # subpackage scores
    score=$(grep $package$s $rawfile | gawk '{n++; x+=$1} END {print int(x/n)}')
    score2=$[$score/10]

    echo "<tr><td align=right>$score% <img src=\"/jumble/$score2.gif\"></td><td><a href=\"/cgi-bin/jumble-cgi?$package$s\">$s</a></td></tr>"
done

echo "</table>"

echo "</td><td>"

# class links/summaries

echo "<table>"

grep $package $rawfile | gawk '{print $1" "$2" "$3" "$3" "$4}' | sed "s|$jumbledir$package||" | gawk '{if (index($3,"/") == 0) print $0}' | gawk '{image=int($1/10); if ($2=="0") { if ($1=="0%") { if (index($4,"gui") != 0) image="pointer"; else image="bad"; } else if ($1=="100%") image="free";}; print "<tr><td align=right>"$1" <img src=\"/jumble/"image".gif\"></td><td align=right>["$2"]</td><td><a href=\"/jumble/"$4".txt\">"$3"</a> "$5"</td></tr>"}'

echo "</table>"

echo "</td></tr></table>"

echo "</body>"
echo "</html>"

